Vagrant.configure(2) do |config|
    config.vm.define "1-networking" do |s1|
        s1.vm.box = "ubuntu/jammy64"
        s1.vm.hostname = "1-networking"
        s1.vm.network "private_network", ip: "192.168.60.2"
    end
    config.ssh.insert_key = false
    config.vm.box_check_update = false
    config.vbguest.auto_update = false
  end
  